server:
  port: 8080
spring:
  application:
    name: Accounts APIx
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always # Permitir cargar scripts sql al iniciar la API
  jpa:
    hibernate:
      ddl-auto: create-drop  # Eliminar y recrear tablas al iniciar la API
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true # Posponer la creacion de las tablas al iniciar la API

